
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./FlowSync/backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./FlowSync/backend/.env
    depends_on:
      - mongo
    restart: always

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - WEBHOOK_URL=https://002e4b437232.ngrok-free.app # placeholder until ngrok tunnel is up
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mongo
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: "start --config /etc/ngrok.yml --all"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040" # optional: view tunnel info via localhost:4040
    depends_on:
      - n8n
    restart: unless-stopped

volumes:
  mongo_data:
  n8n_data:
